# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b670efcb0fd5af68f43b82bd6a68daf64eeda70df4a6ee68ff68fccf3856a4a7a29896c04efa263390871da2d2f0505daca6428119c42575a5eff173adba6ebe

test:
  secret_key_base: c676fc1aff6333b9ebcf0cc3dcff469aa08091f8e5cb736970152937ab5ff0dd8e83bc05984ad6a45fcbb80a4993852de3fe2e559b73adbb0da8d1040160b7ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
